"""
Translator — renders the Librarian-verified English quote in a second language
for the Quote Card product line.

Honesty contract (constitution principles 3 and 9): an LLM translation of
scripture is NOT an official rendering. Every translation this module returns
carries two disclaimers — one in the target language (printed on the card, for
the person who will actually read the translation) and one in English (stored
with the product and shown on the dashboard). Both are fixed strings appended
IN CODE, never generated by the model — the same discipline as
scribe._sanitize_claims: LLM compliance is never trusted for honesty-critical
text.

Adding a language later is a config change only: add an entry to LANGUAGES
(fonts must actually contain the script's glyphs — verify a rendered card
visually before shipping it; see card_compositor.py).
"""

import json
import re

from agents.router import call_llm

# code → language config. font_paths are tried in order by the card
# compositor; every path listed for a script was verified to render real
# glyphs (not tofu) on this machine — see the font-probe check in the
# quote-card work, 2026-07. rtl languages are shaped with arabic_reshaper +
# python-bidi at render time.
LANGUAGES = {
    "es": {
        "name": "Spanish",
        "native_name": "Español",
        "rtl": False,
        # None → the compositor's default serif stack (Palatino/Georgia)
        # covers Spanish diacritics.
        "font_paths": None,
        "disclaimer_native": "Traducción asistida por IA · no es una traducción oficial",
        # Regex of characters the translation MUST contain — a sanity check
        # that the model actually translated. Latin-script languages check
        # for common accented letters OR plain words; kept permissive.
        "script_check": None,
    },
    "zh": {
        "name": "Mandarin Chinese",
        "native_name": "中文",
        "rtl": False,
        "font_paths": [
            "C:/Windows/Fonts/simsun.ttc",   # SimSun — serif (Song), matches Palatino
            "C:/Windows/Fonts/msyh.ttc",     # Microsoft YaHei — sans fallback
        ],
        "disclaimer_native": "人工智能辅助翻译 · 非官方译本",
        "script_check": r"[一-鿿]",
    },
    "ar": {
        "name": "Arabic",
        "native_name": "العربية",
        "rtl": True,
        "font_paths": [
            "C:/Windows/Fonts/times.ttf",    # Times New Roman — Naskh-style Arabic, serif
            "C:/Windows/Fonts/segoeui.ttf",  # Segoe UI — clean fallback
            "C:/Windows/Fonts/tahoma.ttf",
        ],
        "disclaimer_native": "ترجمة بمساعدة الذكاء الاصطناعي · غير رسمية",
        "script_check": r"[؀-ۿ]",
    },
}


def english_disclaimer(lang_code: str) -> str:
    """The dashboard/metadata disclaimer — always English, always stored."""
    name = LANGUAGES.get(lang_code, {}).get("name", lang_code)
    return (f"{name} translation is AI-assisted and unofficial — "
            "not an authorized Bahá'í translation.")


def translate_quote(quote_en: str, lang_code: str) -> dict:
    """
    Translate a verified English quote into LANGUAGES[lang_code].
    Routed to Grok ("creative_writing" task type) — scripture translation
    needs nuance the local model doesn't have.

    Returns {code, name, native_name, rtl, text, disclaimer_native,
    disclaimer_en}. Raises ValueError on an unknown language or a response
    that fails the target-script sanity check — a card must never ship with
    a "translation" that is actually English or model chatter.
    """
    cfg = LANGUAGES.get(lang_code)
    if not cfg:
        raise ValueError(f"Unknown language code: {lang_code!r} — known: {sorted(LANGUAGES)}")

    prompt = (
        f"Translate this Bahá'í quotation from English into {cfg['name']}.\n\n"
        f"\"{quote_en}\"\n\n"
        "Rules:\n"
        "- Faithful and complete: translate the meaning of every phrase; add nothing, omit nothing.\n"
        "- Keep the elevated, reverent register of scripture without archaism for its own sake.\n"
        "- Preserve the line breaks of the original (same number of lines).\n"
        "- No transliteration of the whole text; translate it.\n"
        "- No commentary, no alternatives, no notes.\n\n"
        'Return ONLY this JSON: {"translation": "the translated text, lines separated by \\n"}'
    )
    raw = call_llm(
        "creative_writing",
        [{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=500,
        json_mode=True,
    ).strip()

    try:
        text = str(json.loads(raw).get("translation") or "").strip()
    except (json.JSONDecodeError, AttributeError):
        text = ""
    if not text:
        raise ValueError(f"Translator returned no usable translation for {cfg['name']}: {raw[:200]}")

    # Deterministic sanity checks — never trust the model's own claim of success.
    if cfg["script_check"] and not re.search(cfg["script_check"], text):
        raise ValueError(
            f"Translation for {cfg['name']} contains no {cfg['name']} script "
            f"characters — refusing to ship it: {text[:120]!r}"
        )
    if text.strip().lower() == quote_en.strip().lower():
        raise ValueError(f"Translation for {cfg['name']} is identical to the English source.")

    return {
        "code": lang_code,
        "name": cfg["name"],
        "native_name": cfg["native_name"],
        "rtl": cfg["rtl"],
        "text": text,
        "disclaimer_native": cfg["disclaimer_native"],
        "disclaimer_en": english_disclaimer(lang_code),
    }
