import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import type { CardCopy, Listing, ProductRow, Review } from "./types";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Human labels for the 9 constitution principle keys the Reviewer returns.
export const PRINCIPLE_LABELS: Record<string, string> = {
  "1_work_as_worship": "Work as Worship",
  "2_fruit_not_words": "Judge by Fruit, Not Motion",
  "3_trustworthiness": "Trustworthiness (Amanah)",
  "4_consultation": "Consultation",
  "5_moderation": "Moderation",
  "6_deeds_over_words": "Deeds Over Words",
  "7_craft_in_service": "Craft in Service of Social Good",
  "8_justice": "Justice ('Adl)",
  "9_independent_investigation": "Independent Investigation of Truth",
  // Quote-card rubric keys (reviewer.score_quote_card) — cards are scored on
  // a purpose-built scale, not the 9 Etsy-listing principles.
  quote_citation: "Quote & Citation Accuracy",
  translation: "Translation Honesty & Quality",
  artwork_fit: "Artwork Fit",
  newcomer_accessibility: "Newcomer Accessibility",
  legibility: "Print Legibility",
};

export function principleLabel(key: string): string {
  return PRINCIPLE_LABELS[key] ?? key.replace(/^\d+_/, "").replace(/_/g, " ");
}

export type Badge = "EXCEPTIONAL" | "APPROVED" | "BORDERLINE" | "REJECTED" | "BEST EFFORT" | string;

export function badgeFor(overall: number): Badge {
  if (overall >= 9.0) return "EXCEPTIONAL";
  if (overall >= 7.0) return "APPROVED";
  if (overall >= 5.0) return "BORDERLINE";
  return "REJECTED";
}

/**
 * Badge for a saved product: a product that shipped below its target score
 * (revision loop stalled or ran out of attempts) wears BEST EFFORT so it never
 * looks like a clean pass. target_reached null/undefined = saved before the
 * pipeline tracked this — fall back to the score-range badge.
 */
export function badgeForProduct(row: ProductRow, overall: number): Badge {
  return row.target_reached === 0 ? "BEST EFFORT" : badgeFor(overall);
}

export function badgeClasses(badge: Badge): string {
  switch (badge) {
    case "EXCEPTIONAL":
      return "bg-amber-400/15 text-amber-300 border-amber-400/40";
    case "APPROVED":
      return "bg-emerald-400/10 text-emerald-300 border-emerald-400/40";
    case "BORDERLINE":
    case "BEST EFFORT":
      return "bg-orange-400/10 text-orange-300 border-orange-400/40";
    case "REJECTED":
      return "bg-rose-400/10 text-rose-300 border-rose-400/40";
    default:
      return "bg-slate-700/40 text-slate-300 border-slate-600";
  }
}

export function scoreBarColor(score: number): string {
  if (score >= 9) return "bg-amber-400";
  if (score >= 7) return "bg-emerald-400";
  if (score >= 6) return "bg-orange-400";
  return "bg-rose-400";
}

export const AGENT_COLORS: Record<string, string> = {
  Artist: "border-l-sky-400 text-sky-300",
  Scribe: "border-l-violet-400 text-violet-300",
  Reviewer: "border-l-emerald-400 text-emerald-300",
  Librarian: "border-l-amber-400 text-amber-300",
  System: "border-l-rose-400 text-rose-300",
  Sheraj: "border-l-fuchsia-400 text-fuchsia-300",
};

// The named roster: display name, role label, and avatar for each agent. This
// is a DISPLAY layer only — the backend still keys everything on the stable
// lowercase ids (state.AGENT_NAMES, log_run, consultation labels), so trust
// history and logs carry across the rename untouched. Avatars are generated by
// the Artist pipeline and gitignored (private, like Abigail's); rosterFor()
// tolerates a missing image (RosterAvatar falls back to an initial).
export interface RosterEntry {
  name: string;
  role: string;
  avatar: string;
}

export const ROSTER: Record<string, RosterEntry> = {
  librarian:  { name: "Ruth",    role: "Bahá'í Librarian",   avatar: "/roster/librarian.jpg" },
  artist:     { name: "Theo",    role: "Artist",      avatar: "/roster/artist.jpg" },
  scribe:     { name: "Clara",   role: "Scribe",      avatar: "/roster/scribe.jpg" },
  reviewer:   { name: "Amos",    role: "Reviewer",    avatar: "/roster/reviewer.jpg" },
  steward:    { name: "Nora",    role: "Steward",     avatar: "/roster/steward.jpg" },
  translator: { name: "Sofia",   role: "Translator",  avatar: "/roster/translator.jpg" },
  secretary:  { name: "Abigail", role: "Secretary",   avatar: "/abigail.jpg" },
  // The Video pipeline's two agents had backend ids but no display identity
  // until the Colony tab gave every node a face (2026-08-13). Same rule as the
  // rest: display only — video_director.py / videographer.py still key on the
  // lowercase ids, so their trust history is untouched by the naming.
  director:     { name: "Silas", role: "Director",     avatar: "/roster/director.jpg" },
  videographer: { name: "Marta", role: "Videographer", avatar: "/roster/videographer.jpg" },
};

// The pipeline instruments: real rows in task_runs (so they carry the handoff
// graph) but not people. They render as small unnamed nodes — no avatar, no
// chat, no settings — because pretending a render step is a colleague would
// make the graph lie about who is actually doing the judging.
export const INSTRUMENT_LABELS: Record<string, string> = {
  compositor: "Compositor",
  consultation: "Consultation",
};

export function agentLabel(id: string): string {
  return ROSTER[id]?.name ?? INSTRUMENT_LABELS[id] ?? id.charAt(0).toUpperCase() + id.slice(1);
}

export function agentRole(id: string): string {
  return ROSTER[id]?.role ?? (INSTRUMENT_LABELS[id] ? "pipeline step" : "agent");
}

// Team accent → the concrete colours the constellation draws with. Kept as
// explicit literals rather than built from template strings so Tailwind's
// scanner can actually see every class name it needs to emit.
export interface TeamAccent {
  hex: string;        // for SVG strokes/gradients, which Tailwind can't reach
  text: string;
  border: string;
  bg: string;
  dot: string;
}

export const TEAM_ACCENTS: Record<string, TeamAccent> = {
  amber:   { hex: "#fbbf24", text: "text-amber-300",   border: "border-amber-400/40",   bg: "bg-amber-400/10",   dot: "bg-amber-400" },
  sky:     { hex: "#38bdf8", text: "text-sky-300",     border: "border-sky-400/40",     bg: "bg-sky-400/10",     dot: "bg-sky-400" },
  violet:  { hex: "#a78bfa", text: "text-violet-300",  border: "border-violet-400/40",  bg: "bg-violet-400/10",  dot: "bg-violet-400" },
  emerald: { hex: "#34d399", text: "text-emerald-300", border: "border-emerald-400/40", bg: "bg-emerald-400/10", dot: "bg-emerald-400" },
  rose:    { hex: "#fb7185", text: "text-rose-300",    border: "border-rose-400/40",    bg: "bg-rose-400/10",    dot: "bg-rose-400" },
  gold:    { hex: "#e8d48b", text: "text-amber-100",   border: "border-amber-200/30",   bg: "bg-amber-100/10",   dot: "bg-amber-100" },
};

export function accentFor(accent: string | undefined): TeamAccent {
  return TEAM_ACCENTS[accent ?? ""] ?? TEAM_ACCENTS.amber;
}

/** Look up a roster entry by the backend id ("librarian") or the consultation
 *  label ("Librarian"). Returns undefined for non-persona labels (System,
 *  Sheraj) and tool rows (compositor, consultation) that have no named agent. */
export function rosterFor(idOrLabel: string | null | undefined): RosterEntry | undefined {
  if (!idOrLabel) return undefined;
  return ROSTER[idOrLabel.toLowerCase()];
}

export function parseListing(row: ProductRow): Listing | null {
  if (!row.listing_copy) return null;
  try {
    return JSON.parse(row.listing_copy) as Listing;
  } catch {
    return null;
  }
}

export function isQuoteCard(row: ProductRow): boolean {
  return row.product_type === "quote_card";
}

export function parseCardCopy(row: ProductRow): CardCopy | null {
  if (!isQuoteCard(row) || !row.listing_copy) return null;
  try {
    return JSON.parse(row.listing_copy) as CardCopy;
  } catch {
    return null;
  }
}

export function parseReview(row: ProductRow): Review | null {
  if (!row.reviewer_scores) return null;
  try {
    return JSON.parse(row.reviewer_scores) as Review;
  } catch {
    return null;
  }
}

export function formatDate(iso: string | null | undefined): string {
  if (!iso) return "";
  const d = new Date(iso.includes("T") ? iso : iso.replace(" ", "T") + "Z");
  return isNaN(d.getTime()) ? iso : d.toLocaleString();
}

export function usd(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}
